config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_prefix: 'auth'

  root 'users#index'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  concern :searchable do
    get '/search(/page/:page)', action: :search, on: :collection, as: :search
  end

  resources :users, concerns: [:paginatable, :searchable]

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             polymorphic: true
# uncomment next line for Rails >= 5
#             ,optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  include PgSearch

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
    styles: { small: '20x20', med: '40x40', large: '160x160' }

  validates_attachment_content_type :avatar,
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  # FIXME: https://github.com/Casecommons/pg_search/issues/303
  pg_search_scope :search_by_login,
                  against: [:name, :email],
                  using: { trigram:    {},
                           dmetaphone: {},
                           tsearch: { prefix: true,
                                        highlight: {
                                          start_sel: '<mark>',
                                          stop_sel: '</mark>'
                                        }
                                     }
                         },
                  ignoring: [:accents]

  def login
    name.present? ? name : email
  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up,
      keys: [:name, :avatar, { role_ids: [] }]
    devise_parameter_sanitizer.permit :account_update,
      keys: [:name, :avatar, { role_ids: [] }]
  end

  private

  def user_not_authorized
    redirect_to(request.referrer || root_path,
      flash: {alert: "You are not authorized to perform this action."})
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_request_format!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user

  utf8_enforcer_workaround

  responders :flash, :http_cache, Responders::PaginateResponder
  respond_to :html, :json, :js
  # responders and 'respond_wiht' some why not working that way
  # TODO: debug it.

  USERS_MAX_ON_PAGE = 3

  # GET /users
  # GET /users.json
  def index
    # @users = User.page(params[:page]).per USERS_MAX_ON_PAGE
    # respond_with @users
    respond_to do |format|
      format.html do
        @users = User.page(params[:page]).per USERS_MAX_ON_PAGE
      end
      format.json do
        @users = User.all
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to :html, :json
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    respond_to :html
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user,
                      notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user,
                      notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url,
                    notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /users/search
  # GET /users/search.json
  def search
    result = User.search_by_login params[:query]

    if result
      respond_to do |format|
        format.html do
          @users = result.with_pg_search_highlight
            .page(params[:page]).per USERS_MAX_ON_PAGE
          render :index
        end
        format.js # TODO
        format.json do
          @users = result
          render :index
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to :index }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # setup paginate responder
  def per_page
    USERS_MAX_ON_PAGE
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user
    authorize(@user || User)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params_without_password.require(:user).permit :email, :password,
    :password_confirmation, :name, :avatar, { role_ids: [] }
    #                unsafe here a little --------------^
  end

  def params_without_password
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
footer.footer.bg-faded
  .container
    .row
      span.col-md-2.text-muted Copyright&nbsp;&copy;&nbsp;2016
      span.col-md-2.vertical-line
        a> href='mailto:pitometsu@gmail.com' Yuriy&nbsp;Pitomets

app/views/layouts/_header.html.slim
.pos-f-t
  .navbar.navbar-light.navbar-static-top.bg-faded
    .container
      .navbar-header
        = link_to t(Rails.application.class.parent_name), root_path, class: 'navbar-brand'
      .navbar-right.pull-xs-right
        ul.nav.navbar-nav
          - if user_signed_in?
            - if current_user.avatar.present?
              li.nav-item
                = link_to image_tag(current_user.avatar.url :med), current_user.avatar.url
            li.nav-item
              = link_to current_user.login, edit_user_registration_path, class: 'nav-link'
            li.nav-item
              = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'
          - else
            li.nav-item
              = link_to 'Sign In', new_user_session_path, class: 'nav-link'
            li.nav-item
              = link_to 'Sign Up', new_user_registration_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Workspace
    / fix bootstrap tooltip
    script src='https://www.atlasestateagents.co.uk/javascript/tether.min.js'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield :head if content_for? :head
  body
    = render partial: '/layouts/header'
    .container
      / TODO: refactore duplicate condition!
      /       see: gem bootstrap_flash_messages
      - if notice.present? or alert.present?
        .container
          - if notice.present?
            p.notice #{ notice }
          - if alert.present?
            p.alert #{ alert }
      .container.content
        = yield
    = render partial: '/layouts/footer'

app/views/layouts/devise.html.slim
= content_for :head do
  = stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track' => true

= render template: 'layouts/application'

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  = f.error_notification
  .form-inputs
    = f.input :email, required: true, autofocus: true
    = f.input :name
    = f.input :avatar, as: :file, label_html: { class: 'btn btn-primary' }
    = f.input :password, autocomplete: "off", hint: "leave it blank if you don't want to change it"
    = f.input :password_confirmation
    = f.association :roles, as: :check_boxes, collection: Role.all, label_method: -> (role) { t role.name }
  .form-actions
    = f.button :submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

hr

- if policy(@user).show?
  span.col-md-1
    = link_to 'Show', @user

  span.col-md-1.vertical-line
    = link_to 'Back', users_path
- else
  = link_to 'Back', users_path

app/views/users/index.html.slim
.jumbotron
  h1 Listing users

  / = simple_form_for :search, url: { action: :search }, method: :get, remote: true do |f|
  / = simple_form_for :search, url: search_users_path, method: :get, remote: true do |f|

  = simple_form_for :search, url: { action: :search }, method: :get do |f|
    = f.error_notification
    .form-inputs
      = f.input :query, required: false, placeholder: 'Search...',
        input_html: { name: :query, value: params[:query] }
    .form-actions
      = f.button :submit, 'Search', name: nil


= page_entries_info @users

br

= paginate @users


table.table.table-striped
  - @users.each do |user|
    thead
      tr
        th
        / Img
        th Name
        th Mail
        / TODO: remove duplication
        - if user.respond_to? :pg_search_highlight
          th Matches
        th
        / Buttons

    tbody
      tr
        td = image_tag user.avatar.url :small
        td = user.name
        td = user.email
        - if user.respond_to? :pg_search_highlight
          td = user.pg_search_highlight.html_safe
        td.btn-group
          - if policy(user).show?
            = link_to 'Show', user, class: 'btn btn-secondary btn-sm'

          - if policy(user).edit?
            = link_to 'Edit', edit_user_path(user), class: 'btn btn-secondary btn-sm'

          - if policy(user).destroy?
            = button_to 'Destroy', user, class: 'btn btn-secondary btn-sm',
                data: { confirm: 'Are you sure?' },
                method: :delete

hr

= link_to 'New User', new_user_path, class: 'btn btn-secondary'

app/views/users/new.html.slim
h1 New user

== render 'form'

hr

= link_to 'Back', users_path

app/views/users/show.html.slim
p
  = link_to image_tag(@user.avatar.url :large), @user.avatar.url

p
  strong Name:
  = @user.name

hr

- if policy(@user).edit?
  span.col-md-1
    = link_to 'Edit', edit_user_path(@user)

  span.col-md-1.vertical-line
    = link_to 'Back', users_path
- else
  = link_to 'Back', users_path